# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Dotnet run
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0' # SDK Version to use

      - name: Publish prod
        run: dotnet restore; dotnet publish -r linux-x64 --configuration "Release" --self-contained "true" -o ../application;

      - name: Generate deployment package 
        run: cd ../application; zip ../application.zip *; cd ..; zip broker.zip application.zip broker/aws-linux-deployment-manifest.json; ls

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Broker
          environment_name: Broker-env
          version_label: ${{ github.run_id }}
          region: us-west-2
          deployment_package: broker.zip
